apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: redis-standalone-repo
  namespace: demo
spec:
  backend:
    gcs:
      bucket: stash-ci
      prefix: /redisdump
    storageSecretName: gcs-secret