apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: restore-sample-redis
  namespace: demo
  labels:
    kubedb.com/kind: Redis # this label is mandatory if you are using KubeDB to deploy the database.
spec:
  task:
    name: redis-restore-5.0.3
  repository:
    name: gcs-repo
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: restored-redis
  rules:
  - snapshots: [latest]
