apiVersion: kubedb.com/v1alpha1
kind: Redis
metadata:
  name: redis-recovery-test
  namespace: demo
spec:
  version: 5.0.3-v1
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  init:
    stash:
      kind: RestoreSession
      name: sample-redis-restore