apiVersion: v1
description: 'stash-redis - Redis database plugin for Stash by AppsCode'
name: stash-redis
version: 5.0.3
appVersion: 5.0.3
home: https://stash.run
icon: https://cdn.appscode.com/images/products/stash/addons/redis-stash-addon.png
sources:
- https://github.com/stashed/redis
maintainers:
- name: appscode
  email: support@appscode.com
